[package]
name = "izighost-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
izighost-common = { path = "../crates/common" }
tokio = { workspace = true, features = ["full"] }
zbus.workspace = true
zvariant.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
reqwest.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
kreuzberg.workspace = true
leptess.workspace = true
image.workspace = true
clap.workspace = true
base64 = "0.22"
libc = "0.2"
sha2 = "0.10"
aes = "0.8"
cbc = "0.1"

