[package]
name = "izighost-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
secret-service = { version = "5", features = ["rt-tokio-crypto-rust"] }
thiserror.workspace = true
zbus.workspace = true
zvariant = { workspace = true }
